# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Begginer Experience
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A TTRPG space where every game matters and everyone belongs.
  Stories, play, and discoveryâ€”from one curious mind to another.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thebegginerexperience.github.io" # the base hostname & protocol for your site

# Social media usernames (these create footer icons automatically)
# twitter_username: your_twitter_handle
github_username: thebegginerexperience
# linkedin_username: your_linkedin
# youtube_username: your_youtube_channel
# instagram_username: your_instagram
# discord_username: your_discord  # Not supported by default in Minima

# Multiple YouTube channels
youtube_channels:
  - username: "@TheBegginnerExperience" 
    name: "The Begginner Experience"
  - username: "@YourSecondChannel"
    name: "Second Channel"

# Multiple Discord servers
discord_servers:
  - invite: "https://discord.gg/your-server-invite"
    name: "Main Discord"
  - invite: "https://discord.gg/your-second-server"
    name: "Community Discord"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Header pages for navigation (order matters!)
header_pages:
  - blog.markdown  
  - about.markdown
  - casting.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.bak"
